name: weather_app
description: A Flutter weather application
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Weather and HTTP
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  #image processing
  image_picker: ^1.0.7

  # Notifications
  flutter_local_notifications: ^19.4.0

  # Localization and formatting
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Timezone
  timezone: ^0.10.1

  # UI/UX
  lottie: ^3.1.0
  glassmorphism: ^3.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_signin_button: ^2.0.0

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.0
  build_runner: ^2.4.0
  hive_test: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env